---
- name: Configure GRE Tunnel between rtr1 and rtr2
  hosts: all
  vars:
     ansible_network_os: ios
     ansible_connection: local
     ansible_user: ec2-user
     #Variables can be manually set like this:
     #rtr1_public_ip: "34.236.147.137"
     #rtr2_public_ip: "54.209.50.0"
     #or reference dynamically variables tied to the host directly
     #in this case, its grabbing this from the inventory under lab_inventory
     rtr1_public_ip: "{{hostvars['student1-rtr1']['ansible_ssh_host']}}"
     rtr2_public_ip: "{{hostvars['student1-rtr2']['ansible_ssh_host']}}"
  gather_facts: no

  pre_tasks:
  - debug:
      msg: "{{ansible_user}}"

  tasks:
  - name: create tunnel interface to R2
    ios_config:
      lines:
        - 'ip address 10.0.0.1 255.255.255.0'
        - 'tunnel source GigabitEthernet1'
        - 'tunnel destination {{rtr2_public_ip}}'
      parents: interface Tunnel 0
    when:
      - '"rtr1" in inventory_hostname'

  - name: create tunnel interface to R1
    ios_config:
      lines:
        - 'ip address 10.0.0.2 255.255.255.0'
        - 'tunnel source GigabitEthernet1'
        - 'tunnel destination {{rtr1_public_ip}}'
      parents: interface Tunnel 0
    when:
      - '"rtr2" in inventory_hostname'
