---
- set_fact:
    workshop_type: "networking"
  when:
    - networking is defined
    - networking

- set_fact:
    workshop_type: "F5"
  when:
    - f5workshop is defined
    - f5workshop

- set_fact:
    workshop_type: "Linux"
  when:
    - workshop_type is not match("F5")
    - workshop_type is not match("networking")

- name: execute a command with tower
  uri:
    url: https://ansible.rhdemo.io/api/v2/job_templates/22/launch/
    validate_certs: no
    method: POST
    user: public
    password: public
    status_code: [200, 201]
    force_basic_auth: yes
    body:
      extra_vars:
        azure_name_prefix: "{{ azure_name_prefix }}"
        # linklight_user: "{{ linklight_user }}"
        azure_region: "{{ azure_region }}"
        student_total: "{{ student_total }}"
        workshop_type: "{{ workshop_type }}"
    body_format: json
