- name: DNS FOR STUDENT WEBPAGE FOR EASTUS
  become: False
  azure_rm_dnsrecordset:
    state: "{{ storage_state }}"
    zone_name: "{{workshop_dns_zone}}"
    records:
      - entry: "{{username}}.{{azure_name_prefix|lower}}.{{workshop_dns_zone}}"
    record_type: A
  delegate_to: localhost

- name: CERTBOT FOR TOWER
  include_tasks: "tower.yml"
  when: towerinstall
