- name: GRAB ZONE ID
  azure_rm_dnszone:
    zone: "{{workshop_dns_zone}}"
  register: AZUREINFO

- name: GRAB DNS RECORD SET INFORMATION
  azure_rm_dnsrecordset_facts:
    resource_group: "{{azure_name_prefix}}"
    zone_name: "{{workshop_dns_zone}}"
    record_type: A
  register: record_sets

- name: DELETE DNS ENTRIES FOR EACH STUDENT
  become: False
  azure_rm_dnsrecordset:
    resource_group: "{{azure_name_prefix}}"
    relative_name: www
    zone_name: "{{workshop_dns_zone}}"
    state: "{{ storage_state }}"
    records:
      - entry: "student{{item}}.{{azure_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    value: "{{ (records | first | first)['Value'] }}"
  loop: "{{ range(1, student_total + 1)|list }}"
  vars:
    records: '{{record_sets.ResourceRecordSets | selectattr("Name", "match", "student" + item|string + "." + azure_name_prefix|lower + "." + workshop_dns_zone) | map(attribute="ResourceRecords") | list }}'
  when: records
