- name: grab facts for rtr1
  azure_rm_virtualmachine_facts:
    resource_group: "{{azure_name_prefix}}"
    tags: "{{azure_name_prefix}}-{{username}}-rtr1"
  register: rtr1_node_facts
  delegate_to: localhost

- name: grab facts for rtr2
  azure_rm_virtualmachine_facts:
    resource_group: "{{azure_name_prefix}}"
    tags: "{{azure_name_prefix}}-{{username}}-rtr2"
  register: rtr2_node_facts
  delegate_to: localhost

- name: grab facts for rtr3
  azure_rm_virtualmachine_facts:
    resource_group: "{{azure_name_prefix}}"
    tags: "{{azure_name_prefix}}-{{username}}-rtr3"
  register: rtr3_node_facts
  delegate_to: localhost

- name: grab facts for rtr4
  azure_rm_virtualmachine_facts:
    resource_group: "{{azure_name_prefix}}"
    tags: "{{azure_name_prefix}}-{{username}}-rtr4"
  register: rtr4_node_facts
  delegate_to: localhost
